http:
  routers:
    movies-router:
      rule: "PathPrefix(`/movies`)"
      service: movies-service
      entryPoints:
        - web

    auth-router:
      rule: "PathPrefix(`/auth`)"
      service: auth-service
      entryPoints:
        - web
      middlewares:
        - auth-strip-prefix

  middlewares:
    auth-strip-prefix:
      stripPrefix:
        prefixes:
          - "/auth"

  services:
    movies-service:
      loadBalancer:
        servers:
          - url: "http://movies1:8000"
          - url: "http://movies2:8000"
          - url: "http://movies3:8000"

    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth:8000"
